import { IconType } from "react-icons"

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2"

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi"

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaWhatsapp,
} from "react-icons/fa6"

import {
  TbBrandHtml5,
  TbBrandCss3,
  TbBrandJavascript,
  TbBrandTypescript,
  TbBrandPhp,
  TbBrandNodejs,
  TbBrandReact,
  TbBrandLaravel,
  TbBrandVue,
  TbBrandNextjs,
  TbBrandMysql,
  TbBrandGit,
  TbBrandGithub,
  TbBrandPrisma,
  TbBrandFigma,
  TbBrandAdobeXd,
  TbBrandAdobeIllustrator,
  TbBrandTailwind,
} from "react-icons/tb"
import {
  SiArduino,
  SiCanva,
  SiCodeigniter,
  SiDocker,
  SiExpress,
  SiInkscape,
  SiJquery,
  SiLinux,
  SiNginx,
  SiPostgresql,
  SiPostman,
  SiRedis,
  SiRedux,
  SiTestinglibrary,
  SiVite,
} from "react-icons/si"
import { DiRedis } from "react-icons/di"

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  instagram: FaInstagram,
  whatsapp: FaWhatsapp,
  x: FaX,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  html: TbBrandHtml5,
  css: TbBrandCss3,
  javascript: TbBrandJavascript,
  typescript: TbBrandTypescript,
  php: TbBrandPhp,
  node: TbBrandNodejs,
  react: TbBrandReact,
  next: TbBrandNextjs,
  vue: TbBrandVue,
  express: SiExpress,
  laravel: TbBrandLaravel,
  codeigniter: SiCodeigniter,
  mysql: TbBrandMysql,
  postgresql: SiPostgresql,
  linux: SiLinux,
  git: TbBrandGit,
  docker: SiDocker,
  redis: DiRedis,
  arduino: SiArduino,
  prisma: TbBrandPrisma,
  figma: TbBrandFigma,
  xd: TbBrandAdobeXd,
  illustrator: TbBrandAdobeIllustrator,
  inkscape: SiInkscape,
  canva: SiCanva,
  tailwind: TbBrandTailwind,
  jquery: SiJquery,
  nginx: SiNginx,
  qa: SiTestinglibrary,
  postman: SiPostman,
  vite: SiVite,
  redux: SiRedux,
}

export type IconLibrary = typeof iconLibrary
export type IconName = keyof IconLibrary
